### PR TITLE
JdsSelect: create JdsSelect component and story

### PR DESCRIPTION
**Pull request by adrianpdm**
### Task Description
https://trello.com/c/uGr2w1r4/77-select-vuejs

### Changes
- Add `vue-clickaway` package
- Adjust InputText to support Select component
- Create Select component and story

### Note
JdsSelect is currently not filterable

### CODE REVIEW

**Review by Arif9878 — APPROVED** [review]

**Comment by Arif9878** [comment]
@adrianpdm list select not auto hide after click items

**Comment by adrianpdm** [comment]
> @adrianpdm list select not auto hide after click items

Thank you,
JdsSelect accept `autoClose` prop to perform such behavior.
Currently, `autoClose` default to `false`. Should it be set to `true` ?

**Comment by Arif9878** [comment]
> > @adrianpdm list select not auto hide after click items
> 
> Thank you,
> JdsSelect accept `autoClose` prop to perform such behavior.
> Currently, `autoClose` default to `false`. Should it be set to `true` ?

usually single select auto close but multiple select not auto close,  maybe the default set is `true`

**Comment by adrianpdm** [comment]
> > > @adrianpdm list select not auto hide after click items
> > 
> > 
> > Thank you,
> > JdsSelect accept `autoClose` prop to perform such behavior.
> > Currently, `autoClose` default to `false`. Should it be set to `true` ?
> 
> usually single select auto close but multiple select not auto close, maybe the default set is `true`

Okay, will change this asap

**Comment by adrianpdm** [comment]
> > > @adrianpdm list select not auto hide after click items
> > 
> > 
> > Thank you,
> > JdsSelect accept `autoClose` prop to perform such behavior.
> > Currently, `autoClose` default to `false`. Should it be set to `true` ?
> 
> usually single select auto close but multiple select not auto close, maybe the default set is `true`

updated on this [commit](https://github.com/jabardigitalservice/jds-design-system-vue-lib/pull/45/commits/158c865523fd0c276ba46ee79761ebe04ba4462e)

**Review by adzharamrullah — APPROVED** [review]

**Review by yoslie — APPROVED** [review]

**Review by maulanayuseph — APPROVED** [review]

**Pull request merged**
